import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/Homepage/Header/header';
import Main from '../components/Homepage/Main/main';
import Footer from '../components/Homepage/Footer/footer';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Main/>
      <Footer/>

    </>
  )
}

export default Home;
